Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public decimal id_category { get; set; }
        public string category_name { get; set; }
    }
}

Models/SetProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EddsWaffle.Models
{
    public class SetProduct
    {
        public Product Product { get; set; }
        public Category Category { get; set; }
    }
        
}

Controllers/SupervisorController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EddsWaffle.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Data;
using System.Data.Entity;
using EddsWaffle.Util;
using System.Globalization;


namespace EddsWaffle.Controllers
{
    public class SupervisorController : Controller
    {
        private DB_EddsWaffleEntities db = new DB_EddsWaffleEntities();
        // GET: Supervisor
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult SetProduct()
        {
            ArrayList categories = new ArrayList();
            var getcategorylist = db.Category.ToList();
            foreach (var item in getcategorylist)
            {
                categories.Add(item.category_name);
            }
            var categorylist = categories.ToArray();
            ViewBag.Categories = categorylist;
            return View();
        }
        [HttpPost]
        public ActionResult AddProduct(Product processmodel)
        {
            var codecheck = db.Product.FirstOrDefault(a => a.code_product == processmodel.code_product);

            if (codecheck != null)
            {

                return Content("<script language='javascript' type='text/javascript'>alert('Adding Product Failed (Product Code Already Exist) - Please Try Again'); window.location.href = '/Supervisor/SetProduct';</script>");
            }
            else if (processmodel.code_product == null| processmodel.name_product == null | processmodel.price_product == 0)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Error - Please Try Again and Fill The Form Completely'); window.location.href = '/Supervisor/SetProduct';</script>");
            }
           
            else
            {
                using (DB_EddsWaffleEntities db = new DB_EddsWaffleEntities())
                {
                    db.Product.Add(processmodel);
                    db.SaveChanges();
                    return Content("<script language='javascript' type='text/javascript'>alert('New Product Sucessfully Added !'); window.location.href = '/Supervisor/SetProduct';</script>");
                }
            }
            
         
        }
        
        public ActionResult Product_Data([DataSourceRequest] DataSourceRequest product)
        {
            List<Product> show = new List<Product>();
            DB_EddsWaffleEntities dbproduct = new DB_EddsWaffleEntities();
            var showproduct = dbproduct.Product.ToArray();
            for (int i = 0; i < dbproduct.Product.Count(); i++)
            {
                show.Add(showproduct.ElementAt(i));
            }
            return Json(show.ToDataSourceResult(product));
        }

        public ActionResult UpdateProduct([DataSourceRequest] DataSourceRequest request, Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new[] { product }.ToDataSourceResult(request, ModelState));
            }
            else
            {
                return Json(db.Product.ToList());
            }

        }
        public ActionResult DeleteProduct([DataSourceRequest] DataSourceRequest request, Product product)
        {
            Product deleteproduct = db.Product.Find(product.code_product);
            if (deleteproduct == null)
            {
                return Json("Product Not Found");
            }
            db.Product.Remove(deleteproduct);
            db.SaveChanges();
            return Json(db.Product.ToList());
        }

        public ActionResult Category()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category processcategory)
        {
            var categorycheck = db.Category.FirstOrDefault(a => a.category_name == processcategory.category_name);

            if (categorycheck != null)
            {

                return Content("<script language='javascript' type='text/javascript'>alert('Category Is Already Exist - Please Try Again'); window.location.href = '/Supervisor/Category';</script>");
            }
            else if (processcategory.category_name == null)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Error - Please Try Again and Fill The Category Name Correctly'); window.location.href = '/Supervisor/Category';</script>");
            }

            else
            {
                using (DB_EddsWaffleEntities db = new DB_EddsWaffleEntities())
                {
                    db.Category.Add(processcategory);
                    db.SaveChanges();
                    return Content("<script language='javascript' type='text/javascript'>alert('New Category Succesfully Added !'); window.location.href = '/Supervisor/Category';</script>");
                }
            }
        }
        public ActionResult Category_Data([DataSourceRequest] DataSourceRequest category)
        {
            List<Category> show = new List<Category>();
            DB_EddsWaffleEntities dbcategory = new DB_EddsWaffleEntities();
            var showcategory = dbcategory.Category.ToArray();
            for (int i = 0; i < dbcategory.Category.Count(); i++)
            {
                show.Add(showcategory.ElementAt(i));
            }
            return Json(show.ToDataSourceResult(category));
        }

        public ActionResult UpdateCategory([DataSourceRequest] DataSourceRequest request, Category category)
        {
            var categorycheck = db.Category.FirstOrDefault(a => a.category_name == category.category_name);
            if (categorycheck == null)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new[] { category }.ToDataSourceResult(request, ModelState));
            }

            else
            {
                return Json(db.Category.ToList());
            }

        }
        public ActionResult DeleteCategory([DataSourceRequest] DataSourceRequest request, Category category)
        {
            Category deletecategory = db.Category.Find(category.id_category);
            if (deletecategory == null)
            {
                return Json("Category Not Found");
            }
            db.Category.Remove(deletecategory);
            db.SaveChanges();
            return Json(db.Category.ToList());
        }
        
        public ActionResult History()
        {
            return View();
        }
        public ActionResult History_Data([DataSourceRequest] DataSourceRequest history)
        {
            List<TransactionHeader> show = new List<TransactionHeader>();
            DB_EddsWaffleEntities dbhistory = new DB_EddsWaffleEntities();

            var showhistory = dbhistory.TransactionHeader.ToArray();
            for (int i = 0; i < dbhistory.TransactionHeader.Count(); i++)
            {
                show.Add(showhistory.ElementAt(i));
            }
            return Json(show.ToDataSourceResult(history));
        }
        public ActionResult DeleteHistory([DataSourceRequest] DataSourceRequest request, TransactionHeader history)
        {
            TransactionHeader deletehistory = db.TransactionHeader.Find(history.code_transaction);
            db.Configuration.ProxyCreationEnabled = false;
            if (deletehistory == null)
            {
                return Json("Member Not Found");
            }
            db.TransactionHeader.Remove(deletehistory);
            db.SaveChanges();
            return Json(db.TransactionHeader.ToList());
        }

        public ActionResult DetailHistory_Data(Int64 id, [DataSourceRequest] DataSourceRequest details)
        {
            List<DetailTransaction> show = new List<DetailTransaction>();
            DB_EddsWaffleEntities dbdetails = new DB_EddsWaffleEntities();
            db.Configuration.ProxyCreationEnabled = false;
            var showdetails = dbdetails.DetailTransaction.ToArray();
            for (int i = 0; i < dbdetails.DetailTransaction.Count(); i++)
            {
                show.Add(showdetails.ElementAt(i));
            }
            return Json(show.Where(set => set.transaction_code == id).ToDataSourceResult(details));
        }

        public ActionResult SalesMonitoring()
        {

            return View();
        }
        public ActionResult Chart_Data([DataSourceRequest]DataSourceRequest request)
        {
            List<TransactionHeader> result = new List<TransactionHeader>();
            DB_EddsWaffleEntities db = new DB_EddsWaffleEntities();
            var showchart = db.TransactionHeader.ToArray();

            for (int i = 0; i < db.TransactionHeader.Count(); i++)
            {
                result.Add(showchart.ElementAt(i));
            }
            return Json(result);
        }

        public ActionResult Comparison_Data([DataSourceRequest]DataSourceRequest request)
        {

            var revenue = db.TransactionHeader.ToArray();
            var Forecasting = db.Prediction.ToArray();
            List<Prediction> estimate = new List<Prediction>();
            Prediction predict = new Prediction();

            var weekly = db.TransactionHeader.ToList().GroupBy(x => CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(x.date_time, CalendarWeekRule.FirstDay, DayOfWeek.Saturday)).ToArray();
            int counter = 0;
            int[] income = new int[weekly.Count()];
            double[,] Length = new double[weekly.Count() + 4, 4];


Views/Supervisor/Accounts.cshtml
@model EddsWaffle.Models.User
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>

<html>
    <head>
        <link href="~/Content/Supervisor/Accounts.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Accounts</title>
</head>
    <body>
        <div id="newaccountarea">
            <button id="addaccount" class="buttonAccount button-newAccount">Add New Cashier</button>
        </div>
        <div id="myModal" class="modal">
            <!-- Modal content -->
            <div class="form-wrap">
                @{
                        List<SelectListItem> role = new List<SelectListItem>();
                        role.Add(new SelectListItem
                        {
                            Text = "Cashier",
                            Value = "Cashier",
                            Selected = true
                    });
                }

                    @using (Html.BeginForm("AddAccount", "Supervisor", FormMethod.Post))
                    {
                        <h1><center>Add New Cashier</center></h1>
                        @Html.EditorFor(model => model.username, new { htmlAttributes = new { placeholder = "Username" } }) <br>
                        @Html.PasswordFor(model => model.password, new { htmlAttributes = new { placeholder = "Password" } }) <br>
                        @Html.DropDownListFor(model => model.role, role) <br>
                        <input type="submit" id="add-account" value="Add Account">
                    }
                    <input type="button" id="cancel-account" value="Cancel">

                </div>
        </div>

        <script>
            var modal = document.getElementById("myModal");
            var btn = document.getElementById("addaccount");
            var cancel = document.getElementById("cancel-account");
            btn.onclick = function () {
                modal.style.display = "block";
            }

            // When the user clicks on <span> (x), close the modal
            cancel.onclick = function () {
                modal.style.display = "none";
            }
        </script>        
    </body>
</html>

Views/Supervisor/Category.cshtml
@model EddsWaffle.Models.Category

@{
    Layout = "~/Views/Shared/_SupervisorLayout.cshtml";
}
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Supervisor/SetProduct.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/kendo/kendo.material.min.css" />
    <title>Category</title>
</head>
<body>
    <header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand"><img src="~/Resources/Images/edds-waffle-pku.png" width="150" height="100"></img></a>
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <li><a>@Html.ActionLink("Sales-Monitoring", "SalesMonitoring", new { controller = "Supervisor" })</a></liclass="active">
                        <li><a>@Html.ActionLink("History", "History", new { controller = "Supervisor" })</a></li>
                        <li><a>@Html.ActionLink("Trends - Analysis", "Trends", new { controller = "Supervisor" })</a></li>
                        <li><a>@Html.ActionLink("Products", "SetProduct", new { controller = "Supervisor" })</a></li>
                        <li class="active"><a>@Html.ActionLink("Menu - Category", "Category", new { controller = "Supervisor" })</a></li>
                        <li><a>@Html.ActionLink("Sign Out", "LoginAuth", new { controller = "Login" })</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <section class="callaction">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="big-cta">
                        <div class="cta-text">
                            <h2><span>Product</span> - <i>Categories</i></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div id="newcategoryarea">
        <button id="addcategory" class="buttonCategory button-newCategory">Add Category</button>
    </div>
    <div id="kendo-area">
        @(Html.Kendo().Grid<EddsWaffle.Models.Category>()
                                                           .Name("category-grid")
                                                           .Columns(columns =>
                                                           {
                                                               columns.Bound(p => p.category_name).Width(200).Title("Category").Filterable(filter =>
                                                               {
                                                                   filter.Extra(false);
                                                                   filter.Operators(op =>
                                                                   {
                                                                       op.ForString(str =>
                                                                       {
                                                                           str.Clear().Contains("Searhing Category With....");
                                                                       });
                                                                   });
                                                               });
                                                               columns.Command(command => { command.Edit(); command.Destroy(); }).Width(200).Title("Action");
                                                           })
                                                           .Editable(editable => editable.Mode(GridEditMode.InLine))
                                                           .Pageable()
                                                           .Selectable()
                                                           .Scrollable()
                                                           .Filterable(ftb=>ftb.Mode(GridFilterMode.Row))
                                                           .HtmlAttributes(new
                                                           {
                                                               style
                                                                    = "height:700px; " +
                                                                    "right: 30%;" +
                                                                    "width: 120%; " +
                                                                    "margin-top: 3%; " +
                                                                    "font-size:14px;" +
                                                                    "background-color: white;" +
                                                                    "font-family: 'Exo', sans-serif;"
                                                           })
                                                       .DataSource(dataSource => dataSource
                                                           .Ajax()
                                                           .Model(model => model.Id(p => p.id_category))
                                                           .PageSize(15)
                                                           .ServerOperation(true)
                                                           .Read(read => read.Action("Category_Data", "Supervisor"))
                                                           .Update(update => update.Action("UpdateCategory", "Supervisor"))
                                                           .Destroy(update => update.Action("DeleteCategory", "Supervisor"))
                                                           )
        )

    </div>

    <div id="myModal2" class="modal2">
        <div class="form-wrap2">
            @using (Html.BeginForm("AddCategory", "Supervisor", FormMethod.Post))
            {

                <h1><center>Add Category</center></h1>
                @Html.EditorFor(model => model.category_name, new { htmlAttributes = new { placeholder = "Product Category" } }) <br>
                <input type="submit" id="add-category" value="Add Category">
            }
            <input type="button" id="cancel-category" value="Cancel">

        </div>
    </div>

    <script>
        var modal2 = document.getElementById("myModal2");
        var btn2 = document.getElementById("addcategory");
        var cancel2 = document.getElementById("cancel-category");
        btn2.onclick = function () {
            modal2.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        cancel2.onclick = function () {
            modal2.style.display = "none";
        }

    </script>

</body>
</html>

Views/Supervisor/Dashboard.cshtml

@{
    Layout = "~/Views/Shared/_SupervisorLayout.cshtml";
}

<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
<link href="~/Content/Supervisor/Dashboard.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home - Edds Waffle</title>
</head>
<body>

    <section class="callaction">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="big-cta">
                        <div class="cta-text">
                            <h2><span>Point of Sale</span> powered by <i>Edds Waffle</i></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <section id="content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="box">
                                    <div class="box-gray aligncenter">
                                        <h4>Product Management</h4>
                                        <div class="icon">
                                            <i class="fa fa-sticky-note fa-3x"></i>
                                        </div>
                                        <p>
                                            Simply set the brand new product from your restaurant.
                                        </p>

                                    </div>
                                    <div class="box-bottom">
                                        <a href="#">Learn more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="box">
                                    <div class="box-gray aligncenter">
                                        <h4>History</h4>
                                        <div class="icon">
                                            <i class="fa fa-calendar-check-o fa-3x"></i>
                                        </div>
                                        <p>
                                            See the latest report from your transaction history.
                                        </p>

                                    </div>
                                    <div class="box-bottom">
                                        <a href="#">Learn more</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="box">
                                    <div class="box-gray aligncenter">
                                        <h4>Sales Monitoring</h4>
                                        <div class="icon">
                                            <i class="fa fa-area-chart fa-3x"></i>
                                        </div>
                                        <p>
                                            Get the latest information from your historical data.
                                        </p>

                                    </div>
                                    <div class="box-bottom">
                                        <a href="#">Learn more</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- divider -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="solidline">
                        </div>
                    </div>
                </div>
                <!-- end divider -->

            </div>
        </section>
        </body>
        </html>

Views/Supervisor/Reports.cshtml

@{
    Layout = "~/Views/Shared/_SupervisorLayout.cshtml";
    ViewBag.Title = "Members";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Supervisor/Reports.css" rel="stylesheet" />
    <title>Membership</title>
</head>
<body>
    <div id="date-area">
        <div class="demo-section k-content">
            <h4 style="margin-left:25%">Start date:</h4>
            @(Html.Kendo().DatePicker()
                      .Name("start")
                      .Value("10/10/2011")
                      .Max("10/10/2012")
                      .Events(e => e.Change("startChange"))
                      .HtmlAttributes(new { style =
                      "width: 20%;" +
                      "left: 25%;" }) 
            )

            <h4 style="margin-left: 25%">End date:</h4>
            @(Html.Kendo().DatePicker()
                      .Name("end")
                      .Value("10/10/2012")
                      .Min("10/10/2011")
                      .Events(e => e.Change("endChange"))
                      .HtmlAttributes(new { style =
                      "width: 20%;" +
                      "left: 25%;" 
                      })
            )
        </div>

        <script>
    function startChange() {
        var endPicker = $("#end").data("kendoDatePicker"),
            startDate = this.value();

        if (startDate) {
            startDate = new Date(startDate);
            startDate.setDate(startDate.getDate() + 1);
            endPicker.min(startDate);
        }
    }

    function endChange() {
        var startPicker = $("#start").data("kendoDatePicker"),
            endDate = this.value();

        if (endDate) {
            endDate = new Date(endDate);
            endDate.setDate(endDate.getDate() - 1);
            startPicker.max(endDate);
        }
    }

        </script>
    </div>
    <div id="kendo-area">
        @(Html.Kendo().Grid<EddsWaffle.Models.User>()
                                                                    .Name("grid")
                                                                    .Columns(columns =>
                                                                    {
                                                                        columns.Bound(p => p.id_user).Width(100).Title("Report");
                                                                        columns.Command(command => command.Custom("Use").Click("showDetails")).Width(40);
                                                                    })
                                                                    .Selectable()
                                                                    
                                                                    .Pageable()
                                                                    .Sortable()
                                                                    .Scrollable()
                                                                    .Filterable(ftb => ftb.Mode(GridFilterMode.Row))
                                                                    .HtmlAttributes(new
                                                                    {
                                                                        style
                                                                         = "height:100%; " +
                                                                         "right: 30%;" +
                                                                         "width: 100%; " +
                                                                         "margin-top: 5%; " +
                                                                         "font-size:14px;"
                                                                    })
                                                                    .DataSource(dataSource => dataSource
                                                                        .Ajax()
                                                                        .Model(model => model.Id(p => p.username))
                                                                        .PageSize(20)
                                                                        .ServerOperation(true)
                                                                        .Read(read => read.Action("Workflow_Data", "WorkflowManager"))
                                                                        )
        )
    </div>


</body>
</html>